### ISSUE TITLE
Fails with deployer 6.8.0

### ISSUE THREAD

**Issue by indeedhat** [musps/action-deployer-php#5]
When using the master branch deploying fails with the following error
```
unix_listener: cannot bind to path /github/home/.ssh/deployer_deployer@109.  
  xxx.xxx.xxx.mDATpYGUT7UuPAQL: No such file or directory
```

its still working fine with the v0.1.0 release

Honestly this is quite probably an issue with the new version of deployer needing some kind of setting i dont have, i havnt looked into it as the old release works fine for me.

**Comment by skydiver** [comment]
Same here ... temp fix:

replace `uses: musps/action-deployer-php@master` with `uses: musps/action-deployer-php@v0.1.0`

thanks @indeedhat

**Comment by musps** [comment]
Hello
I reverted the last PR until I find a solution with the version 6.8.0
I come back to you as soon I have found a fix!

**Comment by musps** [comment]
Do you have in your recipe this line set to true?

```
set('ssh_multiplexing', true);
```

When it is disabled it works but when it is enabled the error "unix_listener" pops.
When the recipe is run within a Github action container deployer php looks for `ssh` folder in `/github/home/.ssh` and will create a file inside but the folder is missing!

As a workaround I will create the folder manually after the container is mount

I will push the fix in master but first I prefer add some tests and make it runs at every push & pr

**Comment by skydiver** [comment]
@musps i don't have `ssh_multiplexing` on my script
it's true the default value?

**Comment by musps** [comment]
Yes `ssh_multiplexing` is set to true as default value

**Comment by indeedhat** [comment]
ah that is interesting, i had it explicit ally set to true on one project but all my other ones dont have it set either way.

I just did a test on a project and setting it to false does allow the deploy to work just fine but it is significantly slower.

Interestingly if i run dep directly from my dev machine it works just fine with multiplexing enabled using v6.8.

**Comment by skydiver** [comment]
@musps now i'm getting a new error (it worked fine for a few hours)

```
Agent pid 7
Identity added: /tmp/id_rsa (/tmp/id_rsa)
/usr/local/bin/deployer: line 1: html: No such file or directory
/usr/local/bin/deployer: line 2: syntax error near unexpected token `<'
/usr/local/bin/deployer: line 2: `<head><title>404 Not Found</title></head>
```

i'm using `set('ssh_multiplexing', false);` and `uses: musps/action-deployer-php@master`

---

**Edit 1:** it's because https://deployer.org/releases/v6.4.6/deployer.phar doesn't exists ...
**Edit 2:** deployer site is broken, all downloads links returns 404 https://deployer.org/download/

**Comment by musps** [comment]
Yep deployerphp download endpoint is broken :/
Nothing I can do on my side right now sorry

Someone opened an issue on deployer repo here: https://github.com/deployphp/deployer/issues/2204

**Comment by skydiver** [comment]
i know @musps 

just left the comment in case someone else came here with the same problem

**Comment by musps** [comment]
I created a new release v0.2.0 or with master:
https://github.com/musps/action-deployer-php/releases/tag/v0.2.0

I also added some CI test before each new changes
you can find the last ci run here: https://github.com/musps/action-deployer-php/actions/runs/314017810

If everything works as expected we can close this issue

**Comment by indeedhat** [comment]
I can confirm that with the v0.2.0 release it is working perfectly for me on multiple projects.

Seems to be totally fixed, thanks :)
